"""Editable example: convert a positions CSV into a cellSens XML file.

Use this if you want to inspect or manually edit the CSV generated by
``run_threshold_example.py`` before creating the XML for cellSens.
"""

from __future__ import annotations

import csv
from pathlib import Path

from smart_acquisition.cellsens.xml_writer import (
    write_cellsens_positions,
    write_cellsens_targets,
)
from smart_acquisition.models import AcquisitionTile, RectangularRegion, StagePosition
from smart_acquisition.targeting.tile_planner import (
    plan_mixed_positions_and_tilescans,
    plan_positions_for_high_mag_tiles,
)


# ---------------------------------------------------------------------------
# CONFIGURATION
# ---------------------------------------------------------------------------

POSITIONS_CSV = Path("data/overview_scan_threshold_positions.csv")
CELLSENS_TEMPLATE = Path("xml_templates/overview_before_scan.xml")
CELLSENS_OUTPUT = Path("data/overview_scan_threshold_positions.xml")
PLANNED_POSITIONS_CSV = POSITIONS_CSV.with_name(f"{POSITIONS_CSV.stem}_planned.csv")
RECTANGULAR_REGIONS_CSV = POSITIONS_CSV.with_name(
    f"{POSITIONS_CSV.stem}_rectangular_tilescans.csv"
)

# "raw" keeps every CSV position.
# "group_centers" merges nearby detections into one position per nearby group.
# "group_tiles" writes a grid of positions covering each nearby group.
# "mixed_tilescans" writes isolated/one-tile groups as ordinary positions and
# larger groups as native rectangular tile-scan regions.
PLANNING_MODE = "mixed_tilescans"

# Set these to the camera image size and pixel size of the NEW high-mag
# acquisition, not the low-mag overview.
TARGET_IMAGE_WIDTH_PX = 2048
TARGET_IMAGE_HEIGHT_PX = 2048
TARGET_PIXEL_SIZE_X_UM = 0.108
TARGET_PIXEL_SIZE_Y_UM = 0.108
TARGET_TILE_OVERLAP_FRACTION = 0.1
GROUP_MERGE_DISTANCE_FACTOR = 1.0
COVERAGE_MARGIN_UM = 0.0


# ---------------------------------------------------------------------------
# SCRIPT
# ---------------------------------------------------------------------------


def read_positions_csv(path: str | Path) -> list[StagePosition]:
    positions: list[StagePosition] = []
    with Path(path).open("r", newline="", encoding="utf-8") as handle:
        reader = csv.DictReader(handle)
        required_columns = {"x_um", "y_um", "z_um"}
        missing = required_columns - set(reader.fieldnames or [])
        if missing:
            raise ValueError(f"Missing required CSV columns: {sorted(missing)}")

        for index, row in enumerate(reader, start=1):
            name = row.get("name") or f"Position {index}"
            positions.append(
                StagePosition(
                    x_um=float(row["x_um"]),
                    y_um=float(row["y_um"]),
                    z_um=float(row["z_um"]),
                    name=name,
                )
            )
    return positions


def main() -> None:
    positions = read_positions_csv(POSITIONS_CSV)
    target_tile = AcquisitionTile(
        width_px=TARGET_IMAGE_WIDTH_PX,
        height_px=TARGET_IMAGE_HEIGHT_PX,
        pixel_size_x_um=TARGET_PIXEL_SIZE_X_UM,
        pixel_size_y_um=TARGET_PIXEL_SIZE_Y_UM,
        overlap_fraction=TARGET_TILE_OVERLAP_FRACTION,
    )
    if PLANNING_MODE == "mixed_tilescans":
        mixed_plan = plan_mixed_positions_and_tilescans(
            positions,
            tile=target_tile,
            merge_distance_factor=GROUP_MERGE_DISTANCE_FACTOR,
            coverage_margin_um=COVERAGE_MARGIN_UM,
            name_prefix="Planned",
        )
        planned_positions = mixed_plan.point_positions
        rectangular_regions = mixed_plan.rectangular_regions
        position_groups = mixed_plan.groups
    else:
        planned_positions, position_groups = plan_positions_for_high_mag_tiles(
            positions,
            tile=target_tile,
            mode=PLANNING_MODE,
            merge_distance_factor=GROUP_MERGE_DISTANCE_FACTOR,
            coverage_margin_um=COVERAGE_MARGIN_UM,
            name_prefix="Planned",
        )
        rectangular_regions = []

    write_stage_positions_csv(PLANNED_POSITIONS_CSV, planned_positions)
    write_rectangular_regions_csv(RECTANGULAR_REGIONS_CSV, rectangular_regions)
    if rectangular_regions:
        write_cellsens_targets(
            CELLSENS_TEMPLATE,
            CELLSENS_OUTPUT,
            positions=planned_positions,
            rectangular_regions=rectangular_regions,
        )
    else:
        write_cellsens_positions(CELLSENS_TEMPLATE, CELLSENS_OUTPUT, planned_positions)
    print(f"Read positions: {POSITIONS_CSV}")
    print(f"Raw position count: {len(positions)}")
    print(f"Nearby groups: {len(position_groups)}")
    print(f"Planned position count: {len(planned_positions)}")
    print(f"Rectangular tile-scan count: {len(rectangular_regions)}")
    print(f"Planned positions CSV: {PLANNED_POSITIONS_CSV}")
    print(f"Rectangular tile-scan CSV: {RECTANGULAR_REGIONS_CSV}")
    print(f"cellSens XML output: {CELLSENS_OUTPUT}")
    print(f"XML configuration name: {CELLSENS_OUTPUT.stem}")


def write_stage_positions_csv(path: str | Path, positions: list[StagePosition]) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["name", "x_um", "y_um", "z_um"])
        for position in positions:
            writer.writerow(
                [
                    position.name,
                    repr(float(position.x_um)),
                    repr(float(position.y_um)),
                    repr(float(position.z_um)),
                ]
            )


def write_rectangular_regions_csv(
    path: str | Path, regions: list[RectangularRegion]
) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["name", "center_x_um", "center_y_um", "z_um", "width_um", "height_um"])
        for region in regions:
            writer.writerow(
                [
                    region.name,
                    repr(float(region.center_x_um)),
                    repr(float(region.center_y_um)),
                    repr(float(region.z_um)),
                    repr(float(region.width_um)),
                    repr(float(region.height_um)),
                ]
            )


if __name__ == "__main__":
    main()
